name: Autograding

on: [push]

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ./tests -r junit -o test-results.xml

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results.xml